apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  ports:
    - name: port0
      port: 1972
      targetPort: 1972
    - name: port1
      port: 51773
      targetPort: 51773
    - name: port2
      port: 52773
      targetPort: 52773
    - name: port3
      port: 53773
      targetPort: 53773
  selector:
    app: iris
  type: LoadBalancer
